ec/config/routes.rb
Rails.application.routes.draw do

  resources :orders, :only => [:index], :param => nil do
    get ':page', :action => :index, :on => :collection
    post 'search', :on => :collection
    get 'search:page', :action => :search, :on => :collection
  end

  get 'dashboards' => 'dashboards#index'
  get 'dashboards/index'

  get 'logins' => 'logins#index'
  post 'logins' => 'logins#login'
  get 'dashboards/index'
  post 'dashboards/login'

end

ec/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
end

ec/app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
  belongs_to :delivery_address
  belongs_to :customer_status
end

ec/app/models/customer_status.rb
class CustomerStatus < ActiveRecord::Base
end

ec/app/models/delivery_address.rb
class DeliveryAddress < ActiveRecord::Base
  has_many :orders
  has_many :customers
  belongs_to :prefecture
end

ec/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  has_many :order_items
  has_many :orders, through: :order_items
end

ec/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  belongs_to :customer, -> {includes :delivery_address}
  belongs_to :delivery_address, -> {includes :prefecture}
  has_many :order_items
  has_many :items, through: :order_items
end

ec/app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order
end

ec/app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

ec/app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
  has_many :delivery_addresses
end

ec/app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

ec/app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def index
  end

  def login
    redirect_to dashboards_path
  end
end

ec/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.page(params[:page]).per(2)
    @prefectures = Prefecture.all
    @orderStatuses = OrderStatus.all
  end
end

ec/app/helpers/dashboards_helper.rb
module DashboardsHelper
end

ec/app/helpers/logins_helper.rb
module LoginsHelper
end

ec/app/helpers/orders_helper.rb
module OrdersHelper
end

ec/app/views/logins/index.html.erb
<div class="content">
<%= form_for :login, html: {class: 'login-form'} do |f| %>
  <%= image_tag 'ruby-logo.png', {class: 'login-form__logo'}%>
  <%= f.text_field :username, class: 'login-form__text', placeholder: 'Enter Your name' %>
  <%= f.password_field :password, class: 'login-form__text', placeholder: 'Password' %>
  <%= f.submit class: 'login-form__submit', value: 'Login' %>
<% end %>
</div>

ec/app/views/orders/index.html.erb
<%= render 'layouts/navi' %>

<div class="content">
  <h1 class="main-title">受注検索</h1>
  <div class="outer">
    <section class="search__section">
      <%= form_for :order, url: orders_path do |f| %>
      <ul class="search__condition-list">
        <li class="condition-list__label-item"><label class="item__label">キーワード</label></li>
        <li class="condition-list__input-item"><%= f.text_field :keyword, class: "item__input-text" %></li>
        <li class="condition-list__label-item"><label class="item__label">都道府県</label></li>
        <li class="condition-list__input-item"><%= f.select(:prefecture_id, @prefectures.collect {|p| [ p.name, p.id ] }, {}, {class: "item__input-select"}) %></li>
        <li class="condition-list__label-item"><label class="item__label">ステータス</label></li>
        <li class="condition-list__input-item"><%= f.select(:prefecture_id, @orderStatuses.collect {|p| [ p.name, p.id ] }, {}, {class: "item__input-select"}) %></li>
        <li class="condition-list__label-item"><label class="item__label">受注日</label></li>
        <li class="condition-list__input-item">
          <%= f.date_select :created_at, {use_month_numbers: true, end_year: Date.today.year}, class: "item__input-select", prefix: :start_date %>
          ~
          <%= f.date_select :created_at, {use_month_numbers: true, end_year: Date.today.year}, class: "item__input-select" %>
        </li>
        <li class="condition-list__input-item"><%= f.submit value: "検索", class: "item__submit-button" %></li>
      </ul>
      <% end %>
    </section>
    <section class="list__section">
      <p class="list__paginate-message"><%= @orders.total_count %>&nbsp;件&nbsp;ヒット</p>
      <%= paginate @orders %>
      <table class="section__table">
        <thead>
          <tr class="table-head__row">
            <th class="table__head-item" width="15%">顧客名</th>
            <th class="table__head-item" width="10%">配送先</th>
            <th class="table__head-item" width="15%">ステータス</th>
            <th class="table__head-item" width="20%">注文商品</th>
            <th class="table__head-item" width="20%">注文日</th>
            <th class="table__head-item" width="20%"></th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr class="table-body__row">
            <td class="table-body__value"><%= order.customer.name %></td>
            <td class="table-body__value"><%= order.delivery_address.prefecture.name %></td>
            <td class="table-body__value"><%= order.order_status.name %></td>
            <td class="table-body__value">
              <% order.items.each do |item| %>
              <%= item.name %>
              <% end %>
            </td>
            <td class="table-body__value">2015-01-01</td>
            <td class="table-body__value"><button class="table-body__base-button">詳細</button></td>
          </tr>
          <% end %>
        </tbody>

      </table>
      <%= paginate @orders %>
    </section>
  </div>
</div>